version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    build:
      context: requirements/nginx
      dockerfile: dockerfile
    env_file: .env

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: dockerfile
    env_file: .env

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: dockerfile
    env_file: .env
