version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - my_network
    depends_on:
      - wordpress
    restart: always
    ports:
      - "443:443"
    build:
      context: requirements/nginx
      dockerfile: dockerfile
    env_file: .env

  wordpress:
    image: wordpress
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - my_network
    depends_on:
      - mariadb
        #condition: service_healthy
    restart: always
    expose:
      - "9000"
    build:
      context: requirements/wordpress
      dockerfile: dockerfile
    env_file: .env

  mariadb:
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - my_network
    restart: always
    expose:
      - "3306"
    build:
      context: requirements/mariadb
      dockerfile: dockerfile
      args:
        - SQL_NAME=${SQL_NAME}
        - SQL_USER=${SQL_USER}
        - SQL_PWD=${SQL_PWD}
        - SQL_ROOT_PWD=${SQL_ROOT_PWD}
    env_file: .env
      # healthcheck:
      # test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      # interval: 10s
      # timeout: 20s
      #retries: 5
      #start_period: 5s

volumes:
  wordpress_data:
    driver: local
    name: wordpress_data
    driver_opts:
      type: 'none'
      device: '/home/mjulliat/data/wordpress'
      o: 'bind'
  mariadb_data:
    driver: local
    name: mariadb_data
    driver_opts:
      type: 'none'
      device: '/home/mjulliat/data/mariadb'
      o: 'bind'

networks:
  my_network:
    name: my_network
    driver: bridge
