
FROM debian:bullseye

RUN apt-get update -y && \
    apt-get upgrade -y
RUN apt-get install mariadb-server \
                    vim -y

ARG SQL_USER
ARG SQL_NAME
ARG SQL_PWD
ARG SQL_ROOT_PWD

EXPOSE 3306

COPY ./tools/init_db.sh /tmp/init_db.sh

#COPY ./conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

RUN echo ""
RUN echo "[mysqld]" >> /etc/mysql/my.cnf
RUN echo "skip-networking=0" >> /etc/mysql/my.cnf
RUN echo "skip-bind-address" >> /etc/mysql/my.cnf
RUN echo "datadir=/var/lib/mysql" >> /etc/mysql/my.cnft

ENTRYPOINT ["sh", "tmp/init_db.sh"]

CMD ["mysqld"]
#CMD ["sleep", "10000000000000000"]
