
FROM debian:bullseye

RUN apt-get update && apt-get upgrade -y
RUN apt-get install mariadb-server \ 
                    vim -y

RUN mkdir tools

COPY conf/50-server.conf /etc/mysql/mariadb.conf.d/50-server.cnf
COPY tools/init_db.sh tools/init_db.sh

EXPOSE 3306

ENTRYPOINT ["sh", "tools/init_db.sh"]

CMD ["/usr/bin/mysqld_safe"]
