
FROM debian:bullseye

# installation of the service
RUN apt-get update && apt-get upgrade -y
RUN apt-get install vim \
    wget -y
RUN apt-get install php7.4 \
    php-fpm \
    php-mysql \
    mariadb-client -y

COPY conf/www.conf /etc/php/7.4/fpm/pool.d/www.conf

RUN mkdir -p /run/php

COPY ./tools/config_wp.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/config_wp.sh

EXPOSE 9000

ENTRYPOINT ["sh", "/usr/local/bin/config_wp.sh"]

CMD ["/usr/sbin/php-fpm7.4", "-F"]
#CMD ["sleep", "10000000000000000"]
