
FROM debian:bullseye

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install vim -y
RUN apt-get install wget -y

# installation of the php service
RUN apt-get install php7.3\
                    php-fpm\
                    php-mysql\
                    mariadb-client -y

# instalation of wordpress and giving access to root
RUN wget https://fr.wordpress.org/wordpress-6.3-fr_FR.tar.gz -P /var/www
RUN cd /var/www && tar -xzf wordpress-6.3-fr_FR.tar.gz && rm wordpress-6.3-fr_FR.tar.gz
RUN chown -R root:root /var/www/wordpress

#installation of CLI [inteface textuel pour ligne de commande]
RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp

COPY conf/www.conf /etc/php/7.4/fpm/pool.d/www.conf

CMD ["sleep", "90000000000"]
