
FROM debian:bullseye

RUN apt-get update && apt-get upgrade -y
RUN apt-get install nginx -y \
    openssl -y \
    vim -y
RUN mkdir -p /etc/nginx/ssl \
             /var/run/nginx
RUN chmod 775 /var/www/html

COPY tools/index.html /var/www/html/index.html
COPY tools/leRond.jpg /var/www/html/leRond.jpg
COPY conf/nginx.conf /etc/nginx/conf.d
COPY conf/inception.crt /etc/nginx/ssl/inception.crt
COPY conf/inception.key /etc/nginx/ssl/inception.key

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]

