
FROM debian:buster

RUN apt-get update && apt-get upgrade -y && apt-get install nginx -y
RUN apt-get install openssl -y
RUN apt-get install vim -y
RUN apt-get install curl -y
RUN mkdir -p /etc/nginx/ssl
RUN openssl req -x509 -nodes \
    -out /etc/nginx/ssl/inception.crt \
    -keyout /etc/nginx/ssl/inception.key \
    -subj "/C=fr/ST=IDF/L=Lausanne/O=42/OU=42/CN=mjulliat.42.ch/UID=mjullia"
RUN mkdir -p /var/run/nginx
RUN chmod 775 /var/www/html
RUN mv /var/www/html/index.nginx-debian.html /var/www/html/index.html

COPY conf/nginx.conf /etc/nginx/nginx.conf

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]

