
FROM debian:bullseye

RUN apt-get update && apt-get upgrade -y
RUN apt-get install nginx -y
RUN apt-get install openssl -y
RUN apt-get install vim -y
RUN mkdir -p /etc/nginx/ssl
RUN mkdir -p /var/run/nginx
RUN chmod 775 /var/www/html
RUN mv /var/www/html/index.nginx-debian.html /var/www/html/index.html

COPY conf/nginx.conf /etc/nginx/nginx.conf
COPY conf/inception.crt /etc/nginx/ssl/inception.crt
COPY conf/inception.key /etc/nginx/ssl/inception.key

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]

